"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-07-12 21:22:59.300867
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import qorgan.db.types  # noqa: F401 -- custom column types used in the schema

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', qorgan.db.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', qorgan.db.types.UtcDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_settings'))
    )
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('camera_type', sa.Enum('BULLYING', 'CANTEEN', name='cameratype', native_enum=False), nullable=False),
    sa.Column('role', sa.Enum('MAIN_HALL', 'STAIRS', 'OUTDOOR', 'CANTEEN_ENTRY', 'CANTEEN_EXIT', 'CANTEEN_INSIDE', name='camerarole', native_enum=False), nullable=False),
    sa.Column('rtsp_host', sa.String(length=128), nullable=False),
    sa.Column('rtsp_port', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', qorgan.db.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', qorgan.db.types.UtcDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cameras')),
    sa.UniqueConstraint('name', name=op.f('uq_cameras_name'))
    )
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.create_index('ix_cameras_camera_type', ['camera_type'], unique=False)
        batch_op.create_index('ix_cameras_role', ['role'], unique=False)

    op.create_table('meal_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('BREAKFAST', 'LUNCH', 'SNACK', name='mealkind', native_enum=False), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('starts_at', sa.Time(), nullable=False),
    sa.Column('ends_at', sa.Time(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', qorgan.db.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', qorgan.db.types.UtcDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_windows'))
    )
    op.create_table('mode_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('previous_mode', sa.Enum('BULLYING', 'CANTEEN', 'BOTH', 'IDLE', name='systemmode', native_enum=False), nullable=True),
    sa.Column('new_mode', sa.Enum('BULLYING', 'CANTEEN', 'BOTH', 'IDLE', name='systemmode', native_enum=False), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'SCHEDULE', 'STARTUP', name='modesource', native_enum=False), nullable=False),
    sa.Column('switched_at', qorgan.db.types.UtcDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mode_logs'))
    )
    with op.batch_alter_table('mode_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mode_logs_switched_at'), ['switched_at'], unique=False)

    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('external_id_source', sa.Enum('GENERATED', 'ROSTER', name='externalidsource', native_enum=False), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('person_type', sa.Enum('STUDENT', 'STAFF', name='persontype', native_enum=False), nullable=False),
    sa.Column('class_name', sa.String(length=32), nullable=True),
    sa.Column('position', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', qorgan.db.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', qorgan.db.types.UtcDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_persons')),
    sa.UniqueConstraint('external_id', name=op.f('uq_persons_external_id'))
    )
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.create_index('ix_persons_class_name', ['class_name'], unique=False)
        batch_op.create_index('ix_persons_person_type', ['person_type'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('OPERATOR', 'ADMIN', 'DEVELOPER', name='userrole', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', qorgan.db.types.UtcDateTime(), nullable=True),
    sa.Column('created_at', qorgan.db.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', qorgan.db.types.UtcDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('worker_heartbeats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=64), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('STARTING', 'RUNNING', 'DEGRADED', 'STOPPED', 'CRASHED', name='workerstate', native_enum=False), nullable=False),
    sa.Column('last_seen_at', qorgan.db.types.UtcDateTime(), nullable=True),
    sa.Column('restart_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('frames_processed', sa.Integer(), nullable=False),
    sa.Column('created_at', qorgan.db.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', qorgan.db.types.UtcDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_worker_heartbeats')),
    sa.UniqueConstraint('group_name', name=op.f('uq_worker_heartbeats_group_name'))
    )
    op.create_table('canteen_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('meal_window_id', sa.Integer(), nullable=True),
    sa.Column('entry_camera_id', sa.Integer(), nullable=False),
    sa.Column('exit_camera_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('OPEN', 'INSIDE_CONFIRMED', 'CLOSED', name='sessionstate', native_enum=False), nullable=False),
    sa.Column('outcome', sa.Enum('ATE', 'NOT_ATE', 'UNKNOWN', name='sessionoutcome', native_enum=False), nullable=True),
    sa.Column('close_reason', sa.Enum('EXIT_CAMERA', 'TIMEOUT', 'MANUAL', name='closereason', native_enum=False), nullable=True),
    sa.Column('identity_source', sa.Enum('ENTRY', 'INSIDE_LATE_BIND', 'EXIT', 'MANUAL', name='identitysource', native_enum=False), nullable=True),
    sa.Column('identity_score', sa.Float(), nullable=True),
    sa.Column('opened_at', qorgan.db.types.UtcDateTime(), nullable=False),
    sa.Column('closed_at', qorgan.db.types.UtcDateTime(), nullable=True),
    sa.Column('dwell_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', qorgan.db.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', qorgan.db.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entry_camera_id'], ['cameras.id'], name=op.f('fk_canteen_sessions_entry_camera_id_cameras'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exit_camera_id'], ['cameras.id'], name=op.f('fk_canteen_sessions_exit_camera_id_cameras'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meal_window_id'], ['meal_windows.id'], name=op.f('fk_canteen_sessions_meal_window_id_meal_windows'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_canteen_sessions_person_id_persons'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_canteen_sessions'))
    )
    with op.batch_alter_table('canteen_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_canteen_sessions_opened_at'), ['opened_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_canteen_sessions_person_id'), ['person_id'], unique=False)
        batch_op.create_index('ix_canteen_sessions_person_opened', ['person_id', 'opened_at'], unique=False)
        batch_op.create_index('ix_canteen_sessions_state', ['state'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('BULLYING', name='eventtype', native_enum=False), nullable=False),
    sa.Column('occurred_at', qorgan.db.types.UtcDateTime(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('candidate_probability', sa.Float(), nullable=False),
    sa.Column('validation_score', sa.Float(), nullable=False),
    sa.Column('skeleton_confirmed', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.Enum('SUSPICION', 'ALERT', 'CRITICAL', name='severity', native_enum=False), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('snapshot_path', qorgan.db.types.RelPath(length=512), nullable=True),
    sa.Column('clip_path', qorgan.db.types.RelPath(length=512), nullable=True),
    sa.Column('track_ids', sa.String(length=64), nullable=False),
    sa.Column('merged_into_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'REVIEWED', 'CONFIRMED', 'FALSE_POSITIVE', name='eventstatus', native_enum=False), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', qorgan.db.types.UtcDateTime(), nullable=True),
    sa.Column('created_at', qorgan.db.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', qorgan.db.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_events_camera_id_cameras'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merged_into_id'], ['events.id'], name=op.f('fk_events_merged_into_id_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], name=op.f('fk_events_reviewed_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index('ix_events_camera_occurred', ['camera_id', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index('ix_events_status', ['status'], unique=False)

    op.create_table('person_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('path', qorgan.db.types.RelPath(length=512), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('quality_note', sa.Text(), nullable=True),
    sa.Column('created_at', qorgan.db.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', qorgan.db.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_person_photos_person_id_persons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person_photos'))
    )
    with op.batch_alter_table('person_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_photos_person_id'), ['person_id'], unique=False)
        batch_op.create_index('ix_person_photos_sha256', ['sha256'], unique=False)

    op.create_table('face_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('normalized', sa.Boolean(), nullable=False),
    sa.Column('vector', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', qorgan.db.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', qorgan.db.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_face_embeddings_person_id_persons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photo_id'], ['person_photos.id'], name=op.f('fk_face_embeddings_photo_id_person_photos'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_face_embeddings'))
    )
    with op.batch_alter_table('face_embeddings', schema=None) as batch_op:
        batch_op.create_index('ix_face_embeddings_model', ['model_name', 'model_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_face_embeddings_person_id'), ['person_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('TELEGRAM', name='notificationchannel', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'SENT', 'FAILED', name='notificationstatus', native_enum=False), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('provider_message_id', sa.String(length=64), nullable=True),
    sa.Column('sent_at', qorgan.db.types.UtcDateTime(), nullable=True),
    sa.Column('created_at', qorgan.db.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', qorgan.db.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_notifications_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_event_id'), ['event_id'], unique=False)

    op.create_table('recognition_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('occurred_at', qorgan.db.types.UtcDateTime(), nullable=False),
    sa.Column('top1_person_id', sa.Integer(), nullable=True),
    sa.Column('top1_score', sa.Float(), nullable=True),
    sa.Column('top2_score', sa.Float(), nullable=True),
    sa.Column('gap', sa.Float(), nullable=True),
    sa.Column('face_width', sa.Integer(), nullable=True),
    sa.Column('face_height', sa.Integer(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_recognition_attempts_camera_id_cameras'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['canteen_sessions.id'], name=op.f('fk_recognition_attempts_session_id_canteen_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['top1_person_id'], ['persons.id'], name=op.f('fk_recognition_attempts_top1_person_id_persons'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recognition_attempts'))
    )
    with op.batch_alter_table('recognition_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recognition_attempts_occurred_at'), ['occurred_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recognition_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recognition_attempts_occurred_at'))

    op.drop_table('recognition_attempts')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_event_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('face_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_face_embeddings_person_id'))
        batch_op.drop_index('ix_face_embeddings_model')

    op.drop_table('face_embeddings')
    with op.batch_alter_table('person_photos', schema=None) as batch_op:
        batch_op.drop_index('ix_person_photos_sha256')
        batch_op.drop_index(batch_op.f('ix_person_photos_person_id'))

    op.drop_table('person_photos')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_status')
        batch_op.drop_index(batch_op.f('ix_events_occurred_at'))
        batch_op.drop_index('ix_events_camera_occurred')
        batch_op.drop_index(batch_op.f('ix_events_camera_id'))

    op.drop_table('events')
    with op.batch_alter_table('canteen_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_canteen_sessions_state')
        batch_op.drop_index('ix_canteen_sessions_person_opened')
        batch_op.drop_index(batch_op.f('ix_canteen_sessions_person_id'))
        batch_op.drop_index(batch_op.f('ix_canteen_sessions_opened_at'))

    op.drop_table('canteen_sessions')
    op.drop_table('worker_heartbeats')
    op.drop_table('users')
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_index('ix_persons_person_type')
        batch_op.drop_index('ix_persons_class_name')

    op.drop_table('persons')
    with op.batch_alter_table('mode_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mode_logs_switched_at'))

    op.drop_table('mode_logs')
    op.drop_table('meal_windows')
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.drop_index('ix_cameras_role')
        batch_op.drop_index('ix_cameras_camera_type')

    op.drop_table('cameras')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
